# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a608839cbe8e1fafeed7b5cc8313687c80c69b04981f8d2feadf52ddfd02e7c4f424d2939fef138266dd3c296437bbc4bda744d1ca6eaea5cf8357bc55e9882

test:
  secret_key_base: 2c106ad8b2aa2e63fe62ff2d54bfdaecb2faac57460e599a484e3d1cdee1247ab2fe1ee1686d7b13fd7dd5e096dccedf868dea0be0156fae506d72ef44e90599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
